Logviewer Dokumentation
=======================
Kay Roesler <kay.roesler@utiligence.de>
:revnumber: {project-version}
:revdate: {project-release-date}
:compat-mode!:
:imagesdir: ./images

[[intro]]
== Einführung
Diese Dokumentation ist als Unterstützung für die Administration und Weiterentwicklung des Logviewers vorgesehen.
Es richtet sich an Administratoren und Java Entwickler.

=== Projekt/Dependency/Build Management
Für die Verwaltung der Abhängigkeiten und den Bauvorgang wird Maven eingesetzt.


[[overwiew]]
== Übersicht

Das folgende Blockdiagramm zeigt den grundlegenden Aufbau.
```
 _______    _________    _______
|Browser|--|logviewer|--|logfile|
|_______|  |_________|  |_______|

```
Der Logviewer läuft auf dem HES des GWA. Per Browser wird die Web-UI des Logviewer aufgerufen.
Die Aufrufparameter tenant und logfile definieren, welche Logdatei in welchem Mandanten angezeigt werden soll.
Zusätzlich muss der Parameter path angegeben werden. Entweder mit leerem Inhalt oder mit dem Inhalt `current`.
Änderungen am aufgerufenen Log werden dann wie bei "tail" an den Browser geschickt und angezeigt.


== Installation

Der Logviewer wird sowohl als jar Datei als auch als rpm Paket bereitgestellt.

=== Abhängigkeiten

Es wird Java 8 benötigt. Das rpm Paket setzt als Dependency java-1_8_0-openjdk-headless voraus.

=== RPM

Unter SUSE kann das Paket installiert werden, hier die einzelnen Schritte mit Abhängigkeiten:

  zypper in java-1_8_0-openjdk-headless
  rpm -i logviewer-0.0.1-20190405.102851-2-rpm.rpm

Der Systemd Service ist dann vorhanden, muss aber noch aktiviert werden:

  systemctl enable logviewer.service
  systemctl start logviewer.service

=== Logging

Die verwendete SLES Versionen verwenden journalctl fürs Logging. Zum Einsehen kann beispielsweise aufgerufen werden:

  journalctl -f -u logviewer

=== Struktur

Die Anwendung liegt nach Installation unter /opt/logviewer.
Die Konfiguration liegt nach Installation unter /etc/logviewer/application.yml

== Konfiguration

Die Konfigurationsdatei des Syslog Adapters ist unter /etc/logviewer/application.yml zu finden.

Folgende Inhalte sind konfigurierbar, alles im YAML Format:
(das Attribut wird im properties-Format in der Tabelle dargestellt, muss dann aber als YAML in die YAML Datei.)

[options="header",cols="10,10,80"]
|===
|Attribut   |Typ   |Beschreibung   
//----------------------
|server.servlet.context-path |String   |Context Pfad der Anwendung
|server.servlet.servlet-path |String   |Servlet Pfad der Anwendung
|spring.security.user.name   |String   |Benutzername für Authentifizierung am angebotenen REST Endpoint   
|spring.security.user.password   |String   |Passwort für Authentifizierung am angebotenen REST Endpoint
|configuration.folder   |String |   Pfad des Ordners in dem Mandanten-Logs liegen
|logging.pattern.file   |String   |logback Syntax des Output Formats von Anwendungslogs - nur bei Bedarf ändern   
|logging.level.de.swm   |ENUM   |logback Log Level. Es MUSS mindestens INFO eingestellt werden    
|===



Beispiel:

[source,yaml]
----
server:
  servlet:
    context-path: /logviewer
    servlet-path: /logviewer
###############################################
#
# authentication
#
spring:
  security:
    user:
      name: usertoset
      password: pwtoset
  mvc:
    servlet:
      path: /

###############################################
#
# log folder
#

configuration:
  folder: /opt/smgwa/ess

###############################################
# logging
logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

  level:
    de:
      swm: INFO


----

== Reverse Proxy
Zur Verwendung eines Reverse Proxys, hier apache2, sind folgende Module zu installieren/aktivieren:
* proxy
* proxy_http
* proxy_wstunnel

Zusätzlich ist unter dem annehmenden vhost folgender Teil einzufügen:
[source,config]
----
        # SWM logviewer
        RewriteEngine on
        RewriteCond ${HTTP:UPGRADE} websocket$ [NC]
        RewriteCond ${HTTP:CONNECTION} upgrade$ [NC]
        RewriteRule /(.*) ws:localhost:8080/$1 [P,L]

        ProxyPass /logviewer http://localhost:8080/logviewer
        ProxyPassReverse /logviewer http://localhost:8080/logviewer

----

== Verwendung

Der Logviewer wird im Browser über die zugeordnete URL aufgerufen. Es werden zwei Parameter erwartet, welche über die URL eingegeben werden.

Wurde noch keine Session im Browser geöffnet, wird eine Authentifizierung erzwungen. Es wird Benutzername und Passwort abgefragt.

Folgende Syntax kann verwendet werden:

  http://<server:port>/logviewer/?path=&tenant=<mandant>&logfile=<logdatei>

oder

  http://<server:port>/logviewer/tenant/<mandant>/logfile/<logdatei>

wobei jeweils die in Klammer gesetzten Platzhalter ersetzt werden müssen.

Beispiel:

  http://localhost:8080/logviewer/tenant/tt/logfile/das.txt


== Release Notes

=== 0.0.11

* Verwendung eigener Topics pro Datei um mehrere Logs gleichzeitig einsehen zu können
* Vereinfachung URL durch URL-Pfad statt Parameter
* Einsatz commons.io für log tailing

=== 0.0.10

* Hinzufügen der path Variable in MainController
* Löschen von /current/logs von configuration.folder von application-prod.yaml

=== 0.0.9

* Austausch Log Meldung ERROR gegen WARN bei unerwartetem Leseabbruch

=== 0.0.8

* Austausch Log Meldung ERROR gegen WARN wenn keine lesbare Datei gewählt werden kann

=== 0.0.7
Initiales Release
